---
- name: Install required packages
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: ['dovecot', 'dkimproxy', 'certbot', 'procmail', 'spampd', 'clamsmtp']

- name: ClamAV Tasks
  include_tasks: clamav.yml

- name: Dovecot Tasks
  include_tasks: dovecot.yml

- name: Lets Encrypt Tasks
  include_tasks: letsencrypt.yml

- name: Spam Prevention Tasks
  include_tasks: spam.yml

- name: DKIM Tasks
  include_tasks: dkim.yml

- name: OpenSMTPD Tasks
  include_tasks: opensmtpd.yml

- name: Added e-mail users to system
  user:
    name: "{{ item }}"
  with_items: "{{ users.keys() | list }}"

- name: Setup Procmail for users
  template:
    src: user.procmailrc.j2
    dest: "/home/{{ item }}/.procmailrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
    force: no
  with_items: "{{ users.keys() | list }}"

- name: Add users Maildir
  file:
    path: /home/{{ item }}/Mail
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  with_items: "{{ users.keys() | list }}"

- name: Enable Services
  command: "rcctl enable {{ item }}"
  with_items: ['freshclam', 'clamd', 'cron', 'clamsmtpd', 'dkimproxy_out', 'spampd', 'smtpd', 'dovecot']
