---
- name: Setup assassin
  template: src=spamassassin-local.cf.j2 dest=/etc/mail/spamassassin/local.cf

- name: Custom SpamPD RC Script
  template: src=spampd_custom.j2 dest=/etc/rc.d/spampd_custom mode=0755
  notify: Reload spampd
