---
- name: Setup assassin
  template: src=spamassassin-local.cf.j2 dest=/etc/mail/spamassassin/local.cf

- name: Setup RC Flags for spampd
  lineinfile:
      dest: /etc/rc.conf.local
      regexp: ^spampd_flags
      line: "spampd_flags=\"--port={{ ports.spampd_in }} --relayhost=127.0.0.1:{{ ports.spampd_return }} --tagall -pid=/var/spampd/spampd.pid -aw\""
      create: Yes
  notify: Reload spampd

- name: Certbot Cron
  cron:
    cron_file: /etc/crontab
    user: root
    name: "start spampd"
    special_time: "reboot"
    job: "/etc/rc.d/spampd start"
