---
  - name: set UFW default forward policy to ACCEPT
    lineinfile:
      dest: /etc/default/ufw
      line: DEFAULT_FORWARD_POLICY="ACCEPT"
      regexp: "^DEFAULT_FORWARD_POLICY\\="

  - name: Enable ufw
    ufw: state=enabled policy=allow

  - name: Allow ssh internally
    ufw: rule=allow port=22 direction=in proto=tcp interface={{ private_eth }}

  - name: Allow Docker internally
    ufw: rule=allow port=2376 direction=in proto=tcp interface={{ private_eth }}

  - name: Allow Monitoring internally
    ufw: rule=allow port=19999 direction=in proto=tcp interface={{ private_eth }}

  - name: 80 is open
    ufw: rule=allow port=80 proto=tcp

  - name: 443 is open
    ufw: rule=allow port=443 proto=tcp

  - name: 80 for Docker IPv6 HAProxy is open
    ufw: rule=allow proto=tcp dest={{ docker_ipv6_web }} port=80

  - name: 443 for Docker IPv6 HAProxy is open
    ufw: rule=allow proto=tcp dest={{ docker_ipv6_web }} port=443

  - name: Disable default in
    ufw: direction=incoming policy=deny
    async: 0
    poll: 10
    ignore_errors: true
