---
- name: Install Sysdig Repo Key
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state: present

- name: Setup Sysdig Respository
  apt_repository:
    repo: 'deb https://s3.amazonaws.com/download.draios.com/stable/deb stable-$(ARCH)/'
    state: present
    filename: 'draios'
    update_cache: 'yes'

- name: Install linux linux-headers
  action: shell apt-get install -y linux-headers-$(uname -r) warn=no

- name: Install Sysdig
  apt: name=sysdig state=present
