---
  - name: Setting Private IP Fact
    set_fact: private_ip="{{ servers[ansible_hostname].private_ip }}"

  - name: Load State for IPv6 Subnet
    include_vars:
      file: "{{ provisioner_state_file }}"
      name: state

  - name: Ubuntu Docker Tasks
    include_tasks: ubuntu.yml
    when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

  - name: FreeBSD Docker Tasks
    include_tasks: freebsd.yml
    when: ansible_distribution == 'FreeBSD'

  - name: Enable/Start Docker Service
    service: name=docker enabled=yes state=started

  - name: Create Docker Client Key
    command: openssl genrsa -out {{ client_key }} 4096
    args:
      creates: "{{ client_key }}"
  - import_tasks: servertls.yml
  - import_tasks: clientcrt.yml

  # Docker needs to be setup before Firewall handlers run
  - meta: flush_handlers
