---
  - name: Install Docker
    action: apt name=docker.io

  - name: Disable Local Socket Access for Docker
    lineinfile:
      dest: /lib/systemd/system/docker.service
      regexp: '^ExecStart=\/usr\/bin\/dockerd.*'
      line: "ExecStart=/usr/bin/dockerd"
    register: systemd_target_update

  - name: Reload Systemd targets
    command: systemctl daemon-reload
    when: systemd_target_update.changed
