---
- hosts: all
  vars_files:
    - ../{{ config_file }}
  vars:
    - ansible_python_interpreter: /usr/bin/env python
  roles:
    - root-password
    - private-net
    - ipv6
    - openbsd-basic
    - openbsd-email
    - firewall
